CREATE SCHEMA IF NOT EXISTS `dbtarefa` DEFAULT CHARACTER SET latin1 ;
USE `dbtarefa` ;

CREATE TABLE IF NOT EXISTS `dbtarefa`.`tarefa` (
  `idtarefa` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  `prazo` DATE NULL DEFAULT NULL,
  `concluido` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`idtarefa`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;
